//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class workrec
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Hour { get; set; }
        public Nullable<bool> IsUse { get; set; }
        public string Rmark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
